apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sk055-cm-tls-ingress
  namespace: skala-practice
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: public-nginx
  rules:
    - host: sk055-tls.skala25a.project.skala-ai.com
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: sk055-my-app
                port:
                  number: 8080

          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: sk055-my-app
                port:
                  number: 80
  tls:
    - hosts:
        - sk055-tls.skala25a.project.skala-ai.com
      secretName: sk055-cm-auto-tls-secret
