apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk055-my-app
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk055-my-app
  template:
    metadata:
      labels:
        app: sk055-my-app
    spec:
      containers:
        - name: frontend
          image: amdp-registry.skala-ai.com/skala25a/sk055-webserver:2.0.0
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
