apiVersion: v1
kind: Service
metadata:
  name: sk055-ingress-test
  namespace: skala-practice
spec:
  selector:
    app: sk055-ingress-test
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
