apiVersion: v1
kind: Service
metadata:
  name: sk055-my-app
  namespace: skala-practice
spec:
  selector:
    app: sk055-my-app
  ports:
    - name: http
      protocol: TCP
      port: 8080 # Cluster 내부에서 접근할 포트
      targetPort: 80 # 컨테이너 내부의 Nginx가 80번 포트 열고 있어야 함
  type: ClusterIP
